language: go
go:
  - '1.11'
  - tip

os:
  - osx
  - linux
  - windows

git:
  depth: 3

## Mark Go version 'tip' as an optional.
matrix:
  exclude:
    - go: tip
      os: windows
  allow_failures:
    - go: 'tip'
  fast_finish: true

## Install dependencies and code review tools.
before_install:
  - export GOBIN="${GOPATH}/bin"
  - ./scripts/tools.sh
  - git fetch --tags

## Install all dependencies.
install: |
  export GO111MODULE=on
  if [ "$TRAVIS_OS_NAME" == windows ]; then
    mingw32-make ci-install
  else
    make ci-install
  fi

## Check code, ensure there are no build errors.
script: |
  if [ "$TRAVIS_OS_NAME" == windows ]; then
    mingw32-make ci-test
  else
    make ci-test
  fi

# after_success:
#   - |
#     if [ "$TRAVIS_OS_NAME" == linux ]; then
#       bash <(curl -s https://codecov.io/bash)
#     fi

cache:
  directories:
    ## Preserve golint executable.
    - $GOBIN
    ## Preserve Go module cache.
    - ${GOPATH}/pkg/mod/cache
